### PR TITLE
Add community meet page

### PR DESCRIPTION
**Pull request by IsAmrish**
Signed-off-by: isamrish <askmaurya48@gmail.com>

This commit will add community meet page.

community-meet-page

### CODE REVIEW

**Comment by IsAmrish** [comment]
update-community-meet-2

**Comment by NisantaSahoo** [comment]
@IsAmrish can you please make the following changes 

- remove the periods
- arrange the time zone in ascending

**Comment by IsAmrish** [comment]
@NisantaSahoo  -- as you can see in second screenshot which is updated screenshot. I have arranged time zone and removed periods from list.

**Review by NisantaSahoo — APPROVED** [review]

**Comment by NisantaSahoo** [comment]
@IsAmrish just noticed that there should be double spacing in between calendar invites

**Review by NisantaSahoo — APPROVED** [review]

**Comment by IsAmrish** [comment]
merging it

**Pull request merged**
