### PR TITLE
Update talos.md

### PR DESCRIPTION
**Pull request by Dreadnoth**
Added updated cp.yaml for Talos OS - the previous one causes control plane to crash

### CODE REVIEW

**Review by tiagolobocastro — APPROVED** [review]
Thanks @Dreadnoth, would you be able to modify this for `docs/main/Solutioning/openebs-on-kubernetes-platforms/talos.md` as well?

**Comment by tiagolobocastro** [comment]
Cool thank you, here is fine since it's the same change

**Comment by Dreadnoth** [comment]
@tiagolobocastro done :)

**Review by balaharish7 — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
Thanks @Dreadnoth !

**Pull request merged**
