### PR TITLE
Fixed broken link

### PR DESCRIPTION
**Pull request by xogoodnow**
Fixed the broken link in user guides on Mayastor-installation page

on this page:
https://openebs.io/docs/user-guides/replicated-storage-user-guide/replicated-pv-mayastor/rs-installation

referenced to the following:
https://openebs.io/docs/user-guides/quickstart-guide/installation.md

### CODE REVIEW

**Comment by xogoodnow** [comment]
Hi,
I do not understand the issue with the license here.

https://app.fossa.com/projects/git%2Bgithub.com%2Fopenebs%2Fwebsite/refs/branch/main/1f9c049e41f83e07d90689024be230ef34eecfef/preview

**Comment by tiagolobocastro** [comment]
> Hi,
> 
> I do not understand the issue with the license here. https://app.fossa.com/projects/git%2Bgithub.com%2Fopenebs%2Fwebsite/refs/branch/main/1f9c049e41f83e07d90689024be230ef34eecfef/preview
> 
> Please let me know if there is something that I must do.
> 
> Cheers

Thanks for checking @xogoodnow, there's nothing to do from your side. We started setting up fossa and there's an issue here where we need to request for an exemption. Thanks!

**Review by tiagolobocastro — APPROVED** [review]
If you don't mind could you fix the versioned/4.1 as well? Thanks

**Comment by xogoodnow** [comment]
Hi @tiagolobocastro,
Sure N.P.
Cheers

**Comment by tiagolobocastro** [comment]
Sorry one last ask please, could you amend your commit with DCO?
https://github.com/openebs/website/actions/runs/11784320469/job/32823672832?pr=500

**Review by Abhinandan-Purkait — APPROVED** [review]

**Review by avishnu — APPROVED** [review]

**Pull request merged**
